"""Update TicketStatus enum with new values

Revision ID: 65f8d9a23295
Revises: 4704956d26b8
Create Date: 2025-12-15 15:29:05.985932

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '65f8d9a23295'
down_revision: Union[str, None] = '4704956d26b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE ticketstatus ADD VALUE 'cancelled'")

def downgrade() -> None:
    pass
