"""initial migration

Revision ID: 912d84fff472
Revises: 
Create Date: 2025-05-10 12:33:58.362285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '912d84fff472'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Enum('organizer', 'client', name='userrole'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    schema='core'
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False, schema='core')
    op.create_index('idx_users_is_active', 'users', ['is_active'], unique=False, schema='core')
    op.create_index('idx_users_username', 'users', ['username'], unique=False, schema='core')
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('start_datetime', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('end_datetime', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_ticket_available', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['core.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index('idx_events_created_by', 'events', ['created_by'], unique=False, schema='core')
    op.create_index('idx_events_is_active', 'events', ['is_active'], unique=False, schema='core')
    op.create_index('idx_events_start_datetime', 'events', ['start_datetime'], unique=False, schema='core')
    op.create_index('idx_events_title', 'events', ['title'], unique=False, schema='core')
    op.create_table('tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('available', 'reserved', 'paid', name='ticketstatus'), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('access_level', sa.String(), nullable=True),
    sa.Column('seat', sa.String(), nullable=True),
    sa.Column('room', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expiry_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['core.events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['core.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index('idx_tickets_created_at', 'tickets', ['created_at'], unique=False, schema='core')
    op.create_index('idx_tickets_event_id', 'tickets', ['event_id'], unique=False, schema='core')
    op.create_index('idx_tickets_owner_id', 'tickets', ['owner_id'], unique=False, schema='core')
    op.create_index('idx_tickets_status', 'tickets', ['status'], unique=False, schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tickets_status', table_name='tickets', schema='core')
    op.drop_index('idx_tickets_owner_id', table_name='tickets', schema='core')
    op.drop_index('idx_tickets_event_id', table_name='tickets', schema='core')
    op.drop_index('idx_tickets_created_at', table_name='tickets', schema='core')
    op.drop_table('tickets', schema='core')
    op.drop_index('idx_events_title', table_name='events', schema='core')
    op.drop_index('idx_events_start_datetime', table_name='events', schema='core')
    op.drop_index('idx_events_is_active', table_name='events', schema='core')
    op.drop_index('idx_events_created_by', table_name='events', schema='core')
    op.drop_table('events', schema='core')
    op.drop_index('idx_users_username', table_name='users', schema='core')
    op.drop_index('idx_users_is_active', table_name='users', schema='core')
    op.drop_index('idx_users_email', table_name='users', schema='core')
    op.drop_table('users', schema='core')
    # ### end Alembic commands ###
